### ISSUE TITLE
NOT WORKING WINDOWS 10 PRO

### ISSUE THREAD

**Issue by aza56** [f1nbar/PlaylistsForNewPipe#5]
Hi
When i choose playlist nothing happens.
No button to export playlist.
After changing playlist i get cancel
![Screenshot_5](https://user-images.githubusercontent.com/86070882/122436832-0bcb1c00-cf91-11eb-8c72-8abecce0d003.png)

**Comment by mikwee** [comment]
Same on Fedora Linux, I get this error:
```
Exception in thread "main" java.sql.SQLException: ResultSet closed
        at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
        at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:103)
        at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:393)
        at Extract.connect(Extract.java:91)
        at Main.main(Main.java:7)
```
